name: "🐛 Bug Report"
description: "Report a compilation error or plugin bug in AMXX MultiMod system"
title: "🐛 [Bug]: "
labels: ["type-bug", "priority-medium", "component-plugins"]
body:
  - type: markdown
    attributes:
      value: "## 🐛 Bug Report\nThanks for reporting an issue! Please fill out this form to help us fix the problem."
  
  - type: input
    id: plugin
    attributes:
      label: "🔌 Plugin Name"
      description: "Which plugin is causing the issue?"
      placeholder: "plugin_name.sma"
    validations:
      required: true
  
  - type: input
    id: amxx-version
    attributes:
      label: "📦 AMXX Version"
      description: "What version of AMXX are you using?"
      placeholder: "e.g., 1.9.0"
    validations:
      required: true
  
  - type: input
    id: build-version
    attributes:
      label: "🏗️ Build System Version"
      description: "What version of the build system are you using?"
      placeholder: "e.g., 0.0.5-SNAPSHOT.a1b2c3d"
    validations:
      required: true
  
  - type: dropdown
    id: branch
    attributes:
      label: "🌿 Branch"
      description: "Which branch are you working on?"
      options:
        - "dev"
        - "main"
        - "feature/..."
        - "Other"
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: "🔧 Steps to Reproduce"
      description: "How can we reproduce this issue?"
      placeholder: |
        1. Run: ./compile.sh or GitHub Actions
        2. Error occurs at: [specific step]
        3. ...
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: "📊 Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Successful compilation without errors"
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: "📝 Log Output"
      description: "Paste compile.log or GitHub Actions output here"
      render: shell
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: "🔧 Environment"
      description: "Information about your environment"
      placeholder: |
        OS: [e.g., Ubuntu 22.04, Windows 11]
        Python: [e.g., 3.9]
        GitHub Runner: [e.g., ubuntu-latest]
    validations:
      required: false
  
  - type: textarea
    id: version-info
    attributes:
      label: "🏷️ Version Information"
      description: "Run and paste output of: python3 update_version.py info"
      render: shell
    validations:
      required: false